name: py38_env
channels:
  - nvidia
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=24.2
  - python=3.8.20
  - setuptools=75.1.0
  - sqlite=3.45.3
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - pip:
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - deepdiff==8.4.2
      - docplex==2.29.241
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - orderly-set==5.4.0
      - packaging==24.2
      - pandapower==2.14.11
      - pandas==2.0.3
      - pillow==10.4.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - zipp==3.20.2
